#!/usr/bin/env python2

fibs = [0 for i in xrange(50)]
fibs[0] = fibs[1] = 1
for i in xrange(2, 50):
    fibs[i] = fibs[i - 1] + fibs[i - 2]

nums = [1]
for i in xrange(1, 50):
    nums.append(int(str(nums[i - 1]) + str(fibs[i])))

print(sum(nums))
