#!/usr/bin/env python2

def enc(s):
    v = 0
    z = 2
    x = 1
    res = ''
    for n in xrange(10):
        if n % 5 == 0:
            v += 2
        elif n % 5 == 1:
            v += 3
        elif n % 5 == 2:
            v -= 1;
        elif n % 5 == 3:
            v *= 4
        else:
            v %= 3
        res += s[v]
    return res

letters = [chr(ord('a') + i) for i in xrange(27)]
desired = 'SECRETKEYS'

i = 0
for c in enc(''.join(letters)):
    letters[ord(c) - ord('a')] = desired[i]
    i += 1

print ''.join(letters)
print enc(''.join(letters))
